name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js version compatible with Angular 16
     
      - name: Install Angular CLI
        run: npm install -g @angular/cli@16
     
      - name: Install dependencies
        run: npm install
     
      - name: Build Angular app
        run: ng build --configuration=production --base-href=https://github.com/ina000007/t2.git/
     
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "ina000007@gmail.com"
          git config --global user.name "GitHub Actions"
          echo "t2.github.io" > docs/CNAME
          git add docs
          git commit -m "Deploying to GitHub Pages"
          git push origin HEAD:main



