  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=https://github.com/ina000007/t2
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          echo "your-repo-name.github.io" > docs/CNAME
          git add docs
          git commit -m "Deploying to GitHub Pages"
          git push origin HEAD:main



